# Generated by Django 4.2.7 on 2024-05-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastagem', '0002_alter_calculopastagem_consumo_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculopastagem',
            name='custo',
            field=models.FloatField(null=True, verbose_name='Custo (R$)'),
        ),
        migrations.AlterField(
            model_name='calculopastagem',
            name='numero_piquetes',
            field=models.IntegerField(null=True, verbose_name='Número de Piquetes'),
        ),
        migrations.AlterField(
            model_name='calculopastagem',
            name='peso_vivo',
            field=models.FloatField(null=True, verbose_name='Peso Vivo (Kg)'),
        ),
    ]
